services:
  - type: worker
    name: report-cs-telegram-bot
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8828936242:AAEjg4dj6aiSulWQ3AtbeniO7YOCS8rTjS8
      - key: WEBAPP_URL
        value: https://report-cs-mini-app.pages.dev
